// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using itsm.Infrastructure.Persistence;

#nullable disable

namespace itsm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ItsmDbContext))]
    [Migration("20260926142342_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("itsm.Domain.Entities.AgentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_agent_groups");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_groups_code");

                    b.ToTable("agent_groups", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_user_id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inventory_number");

                    b.Property<DateOnly?>("LicenseExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("license_expiration_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("AssignedUserId")
                        .HasDatabaseName("ix_assets_assigned_user_id");

                    b.HasIndex("InventoryNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_inventory_number");

                    b.ToTable("assets", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.AssetHistoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int?>("NewAssignedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("new_assigned_user_id");

                    b.Property<string>("NewStatus")
                        .HasColumnType("text")
                        .HasColumnName("new_status");

                    b.Property<int?>("OldAssignedUserId")
                        .HasColumnType("integer")
                        .HasColumnName("old_assigned_user_id");

                    b.Property<string>("OldStatus")
                        .HasColumnType("text")
                        .HasColumnName("old_status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asset_history_logs");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_asset_history_logs_asset_id");

                    b.HasIndex("NewAssignedUserId")
                        .HasDatabaseName("ix_asset_history_logs_new_assigned_user_id");

                    b.HasIndex("OldAssignedUserId")
                        .HasDatabaseName("ix_asset_history_logs_old_assigned_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asset_history_logs_user_id");

                    b.ToTable("asset_history_logs", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.CalendarException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("ExceptionDate")
                        .HasColumnType("date")
                        .HasColumnName("exception_date");

                    b.Property<bool>("IsWorkDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_work_day");

                    b.HasKey("Id")
                        .HasName("pk_calendar_exceptions");

                    b.HasIndex("ExceptionDate")
                        .IsUnique()
                        .HasDatabaseName("ix_calendar_exceptions_exception_date");

                    b.ToTable("calendar_exceptions", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.FormTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<JsonElement>("FieldsSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("fields_schema");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_form_templates");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_form_templates_service_id");

                    b.ToTable("form_templates", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.KnowledgeBaseArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_base_articles");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_knowledge_base_articles_service_id");

                    b.ToTable("knowledge_base_articles", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.ReleaseTicketMapping", b =>
                {
                    b.Property<int>("ReleaseTicketId")
                        .HasColumnType("integer")
                        .HasColumnName("release_ticket_id");

                    b.Property<int>("TaskTicketId")
                        .HasColumnType("integer")
                        .HasColumnName("task_ticket_id");

                    b.HasKey("ReleaseTicketId", "TaskTicketId")
                        .HasName("pk_release_ticket_mappings");

                    b.HasIndex("TaskTicketId")
                        .HasDatabaseName("ix_release_ticket_mappings_task_ticket_id");

                    b.ToTable("release_ticket_mappings", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.ServiceCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_service_catalog");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_service_catalog_parent_id");

                    b.ToTable("service_catalog", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.SlaPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ReactionTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("reaction_time_minutes");

                    b.Property<int>("ResolutionTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_time_minutes");

                    b.Property<string>("ScheduleType")
                        .HasColumnType("text")
                        .HasColumnName("schedule_type");

                    b.HasKey("Id")
                        .HasName("pk_sla_policies");

                    b.ToTable("sla_policies", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.SystemRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_system_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_system_roles_code");

                    b.ToTable("system_roles", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ActualReactionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_reaction_time");

                    b.Property<DateTimeOffset?>("ActualResolutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_resolution_time");

                    b.Property<int?>("AssigneeGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("assignee_group_id");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("integer")
                        .HasColumnName("assignee_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_id");

                    b.Property<JsonElement?>("CustomFieldsData")
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields_data");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsReactionEscalated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_reaction_escalated");

                    b.Property<bool>("IsResolutionEscalated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_resolution_escalated");

                    b.Property<DateTimeOffset?>("PlannedEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_end");

                    b.Property<DateTimeOffset?>("PlannedStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_start");

                    b.Property<string>("Priority")
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<int?>("ServiceCatalogId")
                        .HasColumnType("integer")
                        .HasColumnName("service_catalog_id");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<int>("SlaAccumulatedPauseMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sla_accumulated_pause_minutes");

                    b.Property<int?>("SlaPolicyId")
                        .HasColumnType("integer")
                        .HasColumnName("sla_policy_id");

                    b.Property<int?>("SlaPolicyId1")
                        .HasColumnType("integer")
                        .HasColumnName("sla_policy_id1");

                    b.Property<DateTimeOffset?>("SlaReactionDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_reaction_deadline");

                    b.Property<DateTimeOffset?>("SlaResolutionDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_resolution_deadline");

                    b.Property<bool>("SlaTimerPaused")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sla_timer_paused");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("TargetSystem")
                        .HasColumnType("text")
                        .HasColumnName("target_system");

                    b.Property<int?>("TicketStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_status_id");

                    b.Property<int?>("TicketTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_type_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("AssigneeGroupId")
                        .HasDatabaseName("ix_tickets_assignee_group_id");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_tickets_assignee_id");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_tickets_creator_id");

                    b.HasIndex("ServiceCatalogId")
                        .HasDatabaseName("ix_tickets_service_catalog_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_tickets_service_id");

                    b.HasIndex("SlaPolicyId")
                        .HasDatabaseName("ix_tickets_sla_policy_id");

                    b.HasIndex("SlaPolicyId1")
                        .HasDatabaseName("ix_tickets_sla_policy_id1");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_tickets_status_id");

                    b.HasIndex("TicketStatusId")
                        .HasDatabaseName("ix_tickets_ticket_status_id");

                    b.HasIndex("TicketTypeId")
                        .HasDatabaseName("ix_tickets_ticket_type_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_tickets_type_id");

                    b.ToTable("tickets", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.TicketApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproverId")
                        .HasColumnType("integer")
                        .HasColumnName("approver_id");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("step_number");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ticket_approvals");

                    b.HasIndex("ApproverId")
                        .HasDatabaseName("ix_ticket_approvals_approver_id");

                    b.HasIndex("TicketId", "StepNumber")
                        .HasDatabaseName("ix_ticket_approvals_ticket_id_step_number");

                    b.ToTable("ticket_approvals", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.TicketAssetMapping", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.HasKey("TicketId", "AssetId")
                        .HasName("pk_ticket_asset_mappings");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_ticket_asset_mappings_asset_id");

                    b.ToTable("ticket_asset_mappings", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.TicketAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_audit_logs");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_ticket_audit_logs_ticket_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ticket_audit_logs_user_id");

                    b.ToTable("ticket_audit_logs", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.TicketMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("author_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("IsInternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_internal");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_body");

                    b.Property<string>("SourceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("web")
                        .HasColumnName("source_type");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_messages");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_ticket_messages_author_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_ticket_messages_ticket_id");

                    b.ToTable("ticket_messages", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.TicketStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ticket_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_statuses_code");

                    b.ToTable("ticket_statuses", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ticket_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_types_code");

                    b.ToTable("ticket_types", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("manager_id");

                    b.Property<string>("ObjectSid")
                        .HasColumnType("text")
                        .HasColumnName("object_sid");

                    b.Property<string>("TwoFaSecret")
                        .HasColumnType("text")
                        .HasColumnName("two_fa_secret");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("ix_users_manager_id");

                    b.HasIndex("ObjectSid")
                        .IsUnique()
                        .HasDatabaseName("ix_users_object_sid");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.UserRoleMapping", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_role_mappings");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_mappings_role_id");

                    b.ToTable("user_role_mappings", "public");
                });

            modelBuilder.Entity("itsm.Domain.Entities.Asset", b =>
                {
                    b.HasOne("itsm.Domain.Entities.User", "AssignedUser")
                        .WithMany("AssignedAssets")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_assets_users_assigned_user_id");

                    b.Navigation("AssignedUser");
                });

            modelBuilder.Entity("itsm.Domain.Entities.AssetHistoryLog", b =>
                {
                    b.HasOne("itsm.Domain.Entities.Asset", "Asset")
                        .WithMany("HistoryLogs")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_history_logs_assets_asset_id");

                    b.HasOne("itsm.Domain.Entities.User", "NewAssignedUser")
                        .WithMany("NewAssetAssignments")
                        .HasForeignKey("NewAssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_asset_history_logs_users_new_assigned_user_id");

                    b.HasOne("itsm.Domain.Entities.User", "OldAssignedUser")
                        .WithMany("PreviousAssetAssignments")
                        .HasForeignKey("OldAssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_asset_history_logs_users_old_assigned_user_id");

                    b.HasOne("itsm.Domain.Entities.User", "User")
                        .WithMany("AssetHistoryActions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_asset_history_logs_users_user_id");

                    b.Navigation("Asset");

                    b.Navigation("NewAssignedUser");

                    b.Navigation("OldAssignedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("itsm.Domain.Entities.FormTemplate", b =>
                {
                    b.HasOne("itsm.Domain.Entities.ServiceCatalog", "Service")
                        .WithMany("FormTemplates")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_templates_service_catalog_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("itsm.Domain.Entities.KnowledgeBaseArticle", b =>
                {
                    b.HasOne("itsm.Domain.Entities.ServiceCatalog", "Service")
                        .WithMany("KnowledgeBaseArticles")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_knowledge_base_articles_service_catalog_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("itsm.Domain.Entities.ReleaseTicketMapping", b =>
                {
                    b.HasOne("itsm.Domain.Entities.Ticket", "ReleaseTicket")
                        .WithMany("ReleaseMappings")
                        .HasForeignKey("ReleaseTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_release_ticket_mappings_tickets_release_ticket_id");

                    b.HasOne("itsm.Domain.Entities.Ticket", "TaskTicket")
                        .WithMany("IncludedInReleases")
                        .HasForeignKey("TaskTicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_release_ticket_mappings_tickets_task_ticket_id");

                    b.Navigation("ReleaseTicket");

                    b.Navigation("TaskTicket");
                });

            modelBuilder.Entity("itsm.Domain.Entities.ServiceCatalog", b =>
                {
                    b.HasOne("itsm.Domain.Entities.ServiceCatalog", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_catalog_service_catalog_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("itsm.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("itsm.Domain.Entities.AgentGroup", "AssigneeGroup")
                        .WithMany("Tickets")
                        .HasForeignKey("AssigneeGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_agent_groups_assignee_group_id");

                    b.HasOne("itsm.Domain.Entities.User", "Assignee")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_users_assignee_id");

                    b.HasOne("itsm.Domain.Entities.User", "Creator")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_users_creator_id");

                    b.HasOne("itsm.Domain.Entities.ServiceCatalog", null)
                        .WithMany("Tickets")
                        .HasForeignKey("ServiceCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_service_catalog_service_catalog_id");

                    b.HasOne("itsm.Domain.Entities.ServiceCatalog", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_service_catalog_service_id");

                    b.HasOne("itsm.Domain.Entities.SlaPolicy", "SlaPolicy")
                        .WithMany()
                        .HasForeignKey("SlaPolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_sla_policies_sla_policy_id");

                    b.HasOne("itsm.Domain.Entities.SlaPolicy", null)
                        .WithMany("Tickets")
                        .HasForeignKey("SlaPolicyId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_sla_policies_sla_policy_id1");

                    b.HasOne("itsm.Domain.Entities.TicketStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_ticket_statuses_status_id");

                    b.HasOne("itsm.Domain.Entities.TicketStatus", null)
                        .WithMany("Tickets")
                        .HasForeignKey("TicketStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_ticket_statuses_ticket_status_id");

                    b.HasOne("itsm.Domain.Entities.TicketType", null)
                        .WithMany("Tickets")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_ticket_types_ticket_type_id");

                    b.HasOne("itsm.Domain.Entities.TicketType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_ticket_types_type_id");

                    b.Navigation("Assignee");

                    b.Navigation("AssigneeGroup");

                    b.Navigation("Creator");

                    b.Navigation("Service");

                    b.Navigation("SlaPolicy");

                    b.Navigation("Status");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("itsm.Domain.Entities.TicketApproval", b =>
                {
                    b.HasOne("itsm.Domain.Entities.User", "Approver")
                        .WithMany("Approvals")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_approvals_users_approver_id");

                    b.HasOne("itsm.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Approvals")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_approvals_tickets_ticket_id");

                    b.Navigation("Approver");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("itsm.Domain.Entities.TicketAssetMapping", b =>
                {
                    b.HasOne("itsm.Domain.Entities.Asset", "Asset")
                        .WithMany("TicketMappings")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_asset_mappings_assets_asset_id");

                    b.HasOne("itsm.Domain.Entities.Ticket", "Ticket")
                        .WithMany("AssetMappings")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_asset_mappings_tickets_ticket_id");

                    b.Navigation("Asset");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("itsm.Domain.Entities.TicketAuditLog", b =>
                {
                    b.HasOne("itsm.Domain.Entities.Ticket", "Ticket")
                        .WithMany("AuditLogs")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_audit_logs_tickets_ticket_id");

                    b.HasOne("itsm.Domain.Entities.User", "User")
                        .WithMany("TicketAuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_audit_logs_users_user_id");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("itsm.Domain.Entities.TicketMessage", b =>
                {
                    b.HasOne("itsm.Domain.Entities.User", "Author")
                        .WithMany("TicketMessages")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_messages_users_author_id");

                    b.HasOne("itsm.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_messages_tickets_ticket_id");

                    b.Navigation("Author");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("itsm.Domain.Entities.User", b =>
                {
                    b.HasOne("itsm.Domain.Entities.User", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_manager_id");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("itsm.Domain.Entities.UserRoleMapping", b =>
                {
                    b.HasOne("itsm.Domain.Entities.SystemRole", "Role")
                        .WithMany("UserMappings")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_mappings_system_roles_role_id");

                    b.HasOne("itsm.Domain.Entities.User", "User")
                        .WithMany("RoleMappings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_mappings_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("itsm.Domain.Entities.AgentGroup", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("itsm.Domain.Entities.Asset", b =>
                {
                    b.Navigation("HistoryLogs");

                    b.Navigation("TicketMappings");
                });

            modelBuilder.Entity("itsm.Domain.Entities.ServiceCatalog", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("FormTemplates");

                    b.Navigation("KnowledgeBaseArticles");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("itsm.Domain.Entities.SlaPolicy", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("itsm.Domain.Entities.SystemRole", b =>
                {
                    b.Navigation("UserMappings");
                });

            modelBuilder.Entity("itsm.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("AssetMappings");

                    b.Navigation("AuditLogs");

                    b.Navigation("IncludedInReleases");

                    b.Navigation("Messages");

                    b.Navigation("ReleaseMappings");
                });

            modelBuilder.Entity("itsm.Domain.Entities.TicketStatus", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("itsm.Domain.Entities.TicketType", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("itsm.Domain.Entities.User", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("AssetHistoryActions");

                    b.Navigation("AssignedAssets");

                    b.Navigation("AssignedTickets");

                    b.Navigation("CreatedTickets");

                    b.Navigation("DirectReports");

                    b.Navigation("NewAssetAssignments");

                    b.Navigation("PreviousAssetAssignments");

                    b.Navigation("RoleMappings");

                    b.Navigation("TicketAuditLogs");

                    b.Navigation("TicketMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
