CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "object_sid" varchar UNIQUE,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "full_name" varchar NOT NULL,
  "department" varchar,
  "manager_id" integer,
  "is_active" boolean DEFAULT true,
  "two_fa_secret" varchar,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "system_roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE,
  "name" varchar NOT NULL
);

CREATE TABLE "user_role_mappings" (
  "user_id" integer NOT NULL,
  "role_id" integer NOT NULL,
  PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "agent_groups" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE,
  "name" varchar NOT NULL
);

CREATE TABLE "service_catalog" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_id" integer,
  "name" varchar NOT NULL,
  "description" text,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "form_templates" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "service_id" integer NOT NULL,
  "fields_schema" jsonb NOT NULL,
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "ticket_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE,
  "name" varchar NOT NULL
);

CREATE TABLE "ticket_statuses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE,
  "name" varchar NOT NULL
);

CREATE TABLE "sla_policies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "schedule_type" varchar,
  "reaction_time_minutes" integer NOT NULL,
  "resolution_time_minutes" integer NOT NULL
);

CREATE TABLE "calendar_exceptions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "exception_date" date UNIQUE NOT NULL,
  "is_work_day" boolean NOT NULL,
  "description" varchar
);

CREATE TABLE "assets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inventory_number" varchar UNIQUE NOT NULL,
  "name" varchar NOT NULL,
  "category" varchar,
  "serial_number" varchar,
  "status" varchar,
  "license_expiration_date" date,
  "assigned_user_id" integer,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "asset_history_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asset_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "action_type" varchar,
  "old_status" varchar,
  "new_status" varchar,
  "old_assigned_user_id" integer,
  "new_assigned_user_id" integer,
  "comment" text,
  "changed_at" timestamptz DEFAULT (now())
);

CREATE TABLE "tickets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text,
  "type_id" integer NOT NULL,
  "status_id" integer NOT NULL,
  "priority" varchar,
  "service_id" integer,
  "creator_id" integer NOT NULL,
  "assignee_id" integer,
  "assignee_group_id" integer,
  "custom_fields_data" jsonb,
  "sla_policy_id" integer,
  "sla_reaction_deadline" timestamptz,
  "sla_resolution_deadline" timestamptz,
  "is_reaction_escalated" boolean DEFAULT false,
  "is_resolution_escalated" boolean DEFAULT false,
  "actual_reaction_time" timestamptz,
  "actual_resolution_time" timestamptz,
  "sla_timer_paused" boolean DEFAULT false,
  "sla_accumulated_pause_minutes" integer DEFAULT 0,
  "target_system" varchar,
  "planned_start" timestamptz,
  "planned_end" timestamptz,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "ticket_asset_mappings" (
  "ticket_id" integer NOT NULL,
  "asset_id" integer NOT NULL,
  PRIMARY KEY ("ticket_id", "asset_id")
);

CREATE TABLE "release_ticket_mappings" (
  "release_ticket_id" integer NOT NULL,
  "task_ticket_id" integer NOT NULL,
  PRIMARY KEY ("release_ticket_id", "task_ticket_id")
);

CREATE TABLE "ticket_approvals" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_id" integer NOT NULL,
  "approver_id" integer NOT NULL,
  "step_number" integer NOT NULL,
  "status" varchar DEFAULT 'Pending',
  "resolution" text,
  "updated_at" timestamptz
);

CREATE TABLE "knowledge_base_articles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "content" text NOT NULL,
  "service_id" integer,
  "is_published" boolean DEFAULT true,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "ticket_messages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_id" integer NOT NULL,
  "author_id" integer NOT NULL,
  "message_body" text NOT NULL,
  "is_internal" boolean DEFAULT false,
  "source_type" varchar DEFAULT 'web',
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "ticket_audit_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ticket_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "field_name" varchar NOT NULL,
  "old_value" text,
  "new_value" text,
  "changed_at" timestamptz DEFAULT (now())
);

CREATE INDEX ON "ticket_approvals" ("ticket_id", "step_number");

COMMENT ON COLUMN "users"."object_sid" IS 'Идентификатор из Active Directory для синхронизации';

COMMENT ON COLUMN "users"."department" IS 'Используется для авто-доступа руководителей к заявкам отдела';

COMMENT ON COLUMN "users"."manager_id" IS 'Ссылка на руководителя сотрудника (для маршрутов согласования)';

COMMENT ON COLUMN "users"."two_fa_secret" IS 'Секрет для TOTP / 2FA кодов';

COMMENT ON COLUMN "system_roles"."code" IS 'client, manager, resource_owner, security_officer, agent, admin';

COMMENT ON COLUMN "agent_groups"."code" IS 'helpdesk, network_team, security_team, sysadmins';

COMMENT ON COLUMN "agent_groups"."name" IS 'Первая линия, Сетевые инженеры и др.';

COMMENT ON COLUMN "service_catalog"."parent_id" IS 'Для иерархических каталогов услуг';

COMMENT ON COLUMN "form_templates"."service_id" IS 'Связь с каталогом услуг. Unique убран для поддержки наследования (Исправление №1)';

COMMENT ON COLUMN "form_templates"."fields_schema" IS 'JSON-схема полей: типы данных, валидация, видимость для ролей';

COMMENT ON COLUMN "ticket_types"."code" IS 'incident, service_request, change, release, access';

COMMENT ON COLUMN "ticket_statuses"."code" IS 'new, in_progress, on_approval, resolved, closed';

COMMENT ON COLUMN "sla_policies"."name" IS '24x7 Критичный, 8x5 Стандартный';

COMMENT ON COLUMN "sla_policies"."schedule_type" IS '24x7 или 8x5 (учет только 09:00-18:00)';

COMMENT ON COLUMN "calendar_exceptions"."is_work_day" IS 'true - рабочая суббота, false - праздничный день';

COMMENT ON COLUMN "assets"."category" IS 'Hardware, Software License';

COMMENT ON COLUMN "assets"."status" IS 'Purchased, In Use, Repair, Retired';

COMMENT ON COLUMN "assets"."license_expiration_date" IS 'Контроль сроков действия лицензий';

COMMENT ON COLUMN "assets"."assigned_user_id" IS 'Закрепленный сотрудник';

COMMENT ON COLUMN "asset_history_logs"."action_type" IS 'StatusChange, AssignmentChange, Update';

COMMENT ON COLUMN "tickets"."priority" IS 'Low, Medium, High, Critical';

COMMENT ON COLUMN "tickets"."service_id" IS 'Ссылка на каталог услуг';

COMMENT ON COLUMN "tickets"."assignee_id" IS 'Текущий инженер-исполнитель';

COMMENT ON COLUMN "tickets"."assignee_group_id" IS 'Ссылка на справочник групп вместо текста (Исправление №5)';

COMMENT ON COLUMN "tickets"."custom_fields_data" IS 'Заполненные поля формы в формате JSON';

COMMENT ON COLUMN "tickets"."is_reaction_escalated" IS 'Флаг: нарушено время реакции';

COMMENT ON COLUMN "tickets"."is_resolution_escalated" IS 'Флаг: нарушено время решения';

COMMENT ON COLUMN "tickets"."target_system" IS 'Для заявок на доступ: ИС Банка';

COMMENT ON COLUMN "tickets"."planned_start" IS 'Для релизов/изменений: календарное окно выкладки';

COMMENT ON COLUMN "tickets"."planned_end" IS 'Для релизов/изменений: календарное окно выкладки';

COMMENT ON COLUMN "release_ticket_mappings"."release_ticket_id" IS 'ID родительской заявки с типом release';

COMMENT ON COLUMN "release_ticket_mappings"."task_ticket_id" IS 'ID дочерней заявки (incident или change)';

COMMENT ON COLUMN "ticket_approvals"."step_number" IS '1 - Руководитель, 2 - Распорядитель, 3 - ИБ';

COMMENT ON COLUMN "ticket_approvals"."status" IS 'Pending, Approved, Rejected';

COMMENT ON COLUMN "knowledge_base_articles"."content" IS 'Тело статьи в формате Rich Text / HTML';

COMMENT ON COLUMN "knowledge_base_articles"."service_id" IS 'Связь с услугой из каталога для контекстных подсказок пользователям';

COMMENT ON COLUMN "ticket_messages"."message_body" IS 'Rich Text / HTML разметка чата';

COMMENT ON COLUMN "ticket_messages"."is_internal" IS 'Скрытый чат только для инженеров';

COMMENT ON COLUMN "ticket_messages"."source_type" IS 'web, email';

ALTER TABLE "users" ADD FOREIGN KEY ("manager_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_role_mappings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_role_mappings" ADD FOREIGN KEY ("role_id") REFERENCES "system_roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "service_catalog" ADD FOREIGN KEY ("parent_id") REFERENCES "service_catalog" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "form_templates" ADD FOREIGN KEY ("service_id") REFERENCES "service_catalog" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("service_id") REFERENCES "service_catalog" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("type_id") REFERENCES "ticket_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("status_id") REFERENCES "ticket_statuses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("sla_policy_id") REFERENCES "sla_policies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("assignee_group_id") REFERENCES "agent_groups" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_asset_mappings" ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_asset_mappings" ADD FOREIGN KEY ("asset_id") REFERENCES "assets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "release_ticket_mappings" ADD FOREIGN KEY ("release_ticket_id") REFERENCES "tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "release_ticket_mappings" ADD FOREIGN KEY ("task_ticket_id") REFERENCES "tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assets" ADD FOREIGN KEY ("assigned_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asset_history_logs" ADD FOREIGN KEY ("asset_id") REFERENCES "assets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asset_history_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asset_history_logs" ADD FOREIGN KEY ("old_assigned_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asset_history_logs" ADD FOREIGN KEY ("new_assigned_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tickets" ADD FOREIGN KEY ("assignee_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_approvals" ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_approvals" ADD FOREIGN KEY ("approver_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "knowledge_base_articles" ADD FOREIGN KEY ("service_id") REFERENCES "service_catalog" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_messages" ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_messages" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_audit_logs" ADD FOREIGN KEY ("ticket_id") REFERENCES "tickets" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ticket_audit_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
